using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Rms.Infrastructure.Persistence.Migrations.PostgreSql
{
    /// <inheritdoc />
    public partial class AddMasterDataItems : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.EnsureSchema(name: "ref");

            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS ref.master_data_items (
                    master_data_item_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    category_code character varying(100) NOT NULL,
                    item_code character varying(100) NOT NULL,
                    item_name character varying(255) NOT NULL,
                    description character varying(1000) NULL,
                    sort_order integer NOT NULL DEFAULT 100,
                    is_active boolean NOT NULL DEFAULT true,
                    created_at timestamp(0) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    created_by bigint NULL,
                    updated_at timestamp(0) without time zone NULL,
                    updated_by bigint NULL,
                    deleted_at timestamp(0) without time zone NULL,
                    deleted_by bigint NULL,
                    row_version bigint NOT NULL DEFAULT 1
                );

                CREATE UNIQUE INDEX IF NOT EXISTS UQ_master_data_items_category_code
                    ON ref.master_data_items (category_code, item_code)
                    WHERE deleted_at IS NULL;

                INSERT INTO ref.master_data_items (category_code, item_code, item_name, sort_order, is_active)
                SELECT 'research_type', value, value, row_number() OVER (ORDER BY value)::int, true
                FROM (
                    SELECT DISTINCT trim(research_type) AS value
                    FROM research.research_projects
                    WHERE deleted_at IS NULL AND nullif(trim(research_type), '') IS NOT NULL
                ) source
                ON CONFLICT DO NOTHING;

                INSERT INTO ref.master_data_items (category_code, item_code, item_name, sort_order, is_active)
                SELECT 'project_status', value, CASE value
                    WHEN 'not_started' THEN 'Chưa bắt đầu'
                    WHEN 'in_progress' THEN 'Đang thực hiện'
                    WHEN 'completed' THEN 'Hoàn thành'
                    WHEN 'completed_late' THEN 'Hoàn thành trễ'
                    WHEN 'paused' THEN 'Tạm dừng'
                    WHEN 'overdue' THEN 'Trễ hạn'
                    WHEN 'pending' THEN 'Chờ duyệt'
                    WHEN 'revision_required' THEN 'Cần chỉnh sửa'
                    WHEN 'cancelled' THEN 'Hủy'
                    ELSE value
                END, row_number() OVER (ORDER BY value)::int, true
                FROM (
                    SELECT DISTINCT trim(project_status) AS value
                    FROM research.research_projects
                    WHERE deleted_at IS NULL AND nullif(trim(project_status), '') IS NOT NULL
                ) source
                ON CONFLICT DO NOTHING;

                INSERT INTO ref.master_data_items (category_code, item_code, item_name, sort_order, is_active)
                SELECT 'ethics_status', value, CASE value
                    WHEN 'not_required' THEN 'Không yêu cầu'
                    WHEN 'pending' THEN 'Chờ duyệt'
                    WHEN 'approved' THEN 'Đã duyệt'
                    WHEN 'rejected' THEN 'Không được phê duyệt'
                    WHEN 'expired' THEN 'Hết hiệu lực'
                    ELSE value
                END, row_number() OVER (ORDER BY value)::int, true
                FROM (
                    SELECT DISTINCT trim(ethics_status) AS value
                    FROM research.research_projects
                    WHERE deleted_at IS NULL AND nullif(trim(ethics_status), '') IS NOT NULL
                ) source
                ON CONFLICT DO NOTHING;

                INSERT INTO ref.master_data_items (category_code, item_code, item_name, sort_order, is_active)
                SELECT 'current_stage', value, value, row_number() OVER (ORDER BY value)::int, true
                FROM (
                    SELECT DISTINCT trim(current_phase_name) AS value
                    FROM research.research_projects
                    WHERE deleted_at IS NULL AND nullif(trim(current_phase_name), '') IS NOT NULL
                ) source
                ON CONFLICT DO NOTHING;

                INSERT INTO ref.master_data_items (category_code, item_code, item_name, sort_order, is_active)
                SELECT 'risk_level', value, CASE value
                    WHEN 'low' THEN 'Đúng tiến độ'
                    WHEN 'normal' THEN 'Đúng tiến độ'
                    WHEN 'medium' THEN 'Có nguy cơ'
                    WHEN 'high' THEN 'Có nguy cơ'
                    WHEN 'urgent' THEN 'Trễ hạn'
                    WHEN 'critical' THEN 'Trễ hạn'
                    WHEN 'overdue' THEN 'Trễ hạn'
                    WHEN 'completed' THEN 'Đã hoàn thành'
                    WHEN 'completed_late' THEN 'Hoàn thành trễ'
                    WHEN 'paused' THEN 'Tạm dừng'
                    ELSE value
                END, row_number() OVER (ORDER BY value)::int, true
                FROM (
                    SELECT DISTINCT trim(risk_level) AS value
                    FROM research.research_projects
                    WHERE deleted_at IS NULL AND nullif(trim(risk_level), '') IS NOT NULL
                    UNION
                    SELECT DISTINCT trim(priority_level) AS value
                    FROM research.project_milestones
                    WHERE deleted_at IS NULL AND nullif(trim(priority_level), '') IS NOT NULL
                ) source
                ON CONFLICT DO NOTHING;
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DROP TABLE IF EXISTS ref.master_data_items;");
        }
    }
}
