CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'audit') THEN
        CREATE SCHEMA audit;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'ref') THEN
        CREATE SCHEMA ref;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'training') THEN
        CREATE SCHEMA training;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'auth') THEN
        CREATE SCHEMA auth;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'notify') THEN
        CREATE SCHEMA notify;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'research') THEN
        CREATE SCHEMA research;
    END IF;
END $EF$;

CREATE TABLE ref.departments (
    department_id bigint GENERATED BY DEFAULT AS IDENTITY,
    department_code character varying(50) NOT NULL,
    department_name character varying(255) NOT NULL,
    parent_department_id bigint,
    department_type character varying(100),
    description character varying(1000),
    is_active boolean NOT NULL DEFAULT TRUE,
    sort_order integer NOT NULL,
    created_at timestamp(0) with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    created_by bigint,
    updated_at timestamp(0) with time zone,
    updated_by bigint,
    deleted_at timestamp(0) with time zone,
    deleted_by bigint,
    row_version bigint NOT NULL DEFAULT 1,
    CONSTRAINT "PK_departments" PRIMARY KEY (department_id),
    CONSTRAINT "FK_departments_parent" FOREIGN KEY (parent_department_id) REFERENCES ref.departments (department_id)
);

CREATE TABLE training.event_categories (
    category_id bigint GENERATED BY DEFAULT AS IDENTITY,
    category_code character varying(100) NOT NULL,
    category_name character varying(255) NOT NULL,
    description character varying(1000),
    color_class character varying(100),
    sort_order integer NOT NULL,
    is_active boolean NOT NULL DEFAULT TRUE,
    created_at timestamp(0) with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_event_categories" PRIMARY KEY (category_id)
);

CREATE TABLE auth.permissions (
    permission_id bigint GENERATED BY DEFAULT AS IDENTITY,
    module_code character varying(100) NOT NULL,
    module_name character varying(255) NOT NULL,
    action_code character varying(100) NOT NULL,
    action_name character varying(255) NOT NULL,
    permission_code character varying(201) GENERATED ALWAYS AS (module_code || '.' || action_code) STORED,
    description character varying(1000),
    is_active boolean NOT NULL DEFAULT TRUE,
    created_at timestamp(0) with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_permissions" PRIMARY KEY (permission_id)
);

CREATE TABLE auth.roles (
    role_id bigint GENERATED BY DEFAULT AS IDENTITY,
    role_code character varying(100) NOT NULL,
    role_name character varying(255) NOT NULL,
    description character varying(1000),
    is_system boolean NOT NULL,
    is_active boolean NOT NULL DEFAULT TRUE,
    created_at timestamp(0) with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    created_by bigint,
    updated_at timestamp(0) with time zone,
    updated_by bigint,
    deleted_at timestamp(0) with time zone,
    deleted_by bigint,
    row_version bigint NOT NULL DEFAULT 1,
    CONSTRAINT "PK_roles" PRIMARY KEY (role_id)
);

CREATE TABLE ref.system_settings (
    setting_id bigint GENERATED BY DEFAULT AS IDENTITY,
    setting_key character varying(150) NOT NULL,
    setting_value text,
    value_type character varying(50) NOT NULL DEFAULT 'string',
    setting_group character varying(100) NOT NULL DEFAULT 'general',
    setting_name character varying(255) NOT NULL,
    description character varying(1000),
    is_public boolean NOT NULL,
    is_active boolean NOT NULL DEFAULT TRUE,
    created_at timestamp(0) with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    created_by bigint,
    updated_at timestamp(0) with time zone,
    updated_by bigint,
    row_version bigint NOT NULL DEFAULT 1,
    CONSTRAINT "PK_system_settings" PRIMARY KEY (setting_id)
);

CREATE TABLE auth.users (
    user_id bigint GENERATED BY DEFAULT AS IDENTITY,
    username character varying(100) NOT NULL,
    email character varying(255) NOT NULL,
    password_hash character varying(500),
    password_salt character varying(500),
    full_name character varying(255) NOT NULL,
    initials character varying(20),
    phone_number character varying(50),
    avatar_url character varying(1000),
    title character varying(255),
    department_id bigint,
    account_status character varying(50) NOT NULL DEFAULT 'active',
    is_system_admin boolean NOT NULL,
    email_confirmed boolean NOT NULL,
    must_change_password boolean NOT NULL,
    failed_login_count integer NOT NULL,
    locked_until timestamp(0) with time zone,
    last_login_at timestamp(0) with time zone,
    last_login_ip character varying(100),
    password_changed_at timestamp(0) with time zone,
    created_at timestamp(0) with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    created_by bigint,
    updated_at timestamp(0) with time zone,
    updated_by bigint,
    deleted_at timestamp(0) with time zone,
    deleted_by bigint,
    row_version bigint NOT NULL DEFAULT 1,
    CONSTRAINT "PK_users" PRIMARY KEY (user_id),
    CONSTRAINT "FK_users_department" FOREIGN KEY (department_id) REFERENCES ref.departments (department_id)
);

CREATE TABLE audit.activity_logs (
    activity_log_id bigint GENERATED BY DEFAULT AS IDENTITY,
    occurred_at timestamp(0) with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    user_id bigint,
    module_code character varying(100) NOT NULL,
    action_type character varying(100) NOT NULL,
    entity_type character varying(100),
    entity_id bigint,
    entity_code character varying(100),
    action_summary character varying(1000) NOT NULL,
    old_value_json jsonb,
    new_value_json jsonb,
    ip_address character varying(100),
    user_agent character varying(1000),
    request_id character varying(100),
    status character varying(50) NOT NULL DEFAULT 'success',
    error_message text,
    CONSTRAINT "PK_activity_logs" PRIMARY KEY (activity_log_id),
    CONSTRAINT "FK_activity_logs_user" FOREIGN KEY (user_id) REFERENCES auth.users (user_id)
);

CREATE TABLE audit.data_change_logs (
    data_change_log_id bigint GENERATED BY DEFAULT AS IDENTITY,
    occurred_at timestamp(0) with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    user_id bigint,
    table_schema character varying(128) NOT NULL,
    table_name character varying(128) NOT NULL,
    primary_key_value character varying(255) NOT NULL,
    change_type character varying(20) NOT NULL,
    old_value_json jsonb,
    new_value_json jsonb,
    request_id character varying(100),
    CONSTRAINT "PK_data_change_logs" PRIMARY KEY (data_change_log_id),
    CONSTRAINT "FK_data_change_logs_user" FOREIGN KEY (user_id) REFERENCES auth.users (user_id)
);

CREATE TABLE audit.login_events (
    login_event_id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint,
    username_or_email character varying(255),
    event_type character varying(50) NOT NULL,
    success boolean NOT NULL,
    ip_address character varying(100),
    user_agent character varying(1000),
    failure_reason character varying(1000),
    occurred_at timestamp(0) with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_login_events" PRIMARY KEY (login_event_id),
    CONSTRAINT "FK_login_events_user" FOREIGN KEY (user_id) REFERENCES auth.users (user_id)
);

CREATE TABLE auth.login_sessions (
    session_id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    session_token_hash character varying(500),
    ip_address character varying(100),
    user_agent character varying(1000),
    device_name character varying(255),
    login_at timestamp(0) with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    expires_at timestamp(0) with time zone,
    logout_at timestamp(0) with time zone,
    logout_reason character varying(255),
    is_active boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT "PK_login_sessions" PRIMARY KEY (session_id),
    CONSTRAINT "FK_login_sessions_user" FOREIGN KEY (user_id) REFERENCES auth.users (user_id)
);

CREATE TABLE notify.notification_settings (
    notification_setting_id bigint GENERATED BY DEFAULT AS IDENTITY,
    scope_type character varying(50) NOT NULL,
    user_id bigint,
    enable_system_notification boolean NOT NULL DEFAULT TRUE,
    enable_email_notification boolean NOT NULL,
    enable_in_app_notification boolean NOT NULL DEFAULT TRUE,
    deadline_reminder_days_json jsonb NOT NULL DEFAULT '[7,3,1,0]',
    training_event_reminder_days_json jsonb NOT NULL DEFAULT '[7,3,1,0]',
    ethics_reminder_days_json jsonb NOT NULL DEFAULT '[90,30,7]',
    project_end_reminder_days_json jsonb NOT NULL DEFAULT '[30,14,7]',
    progress_report_reminder_days_json jsonb NOT NULL DEFAULT '[7,3,1]',
    daily_scan_time time(0) without time zone NOT NULL DEFAULT TIME '07:00:00',
    repeat_if_overdue boolean NOT NULL DEFAULT TRUE,
    overdue_repeat_days integer NOT NULL DEFAULT 1,
    auto_resolve_when_completed boolean NOT NULL DEFAULT TRUE,
    created_at timestamp(0) with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    updated_at timestamp(0) with time zone,
    updated_by bigint,
    row_version bigint NOT NULL DEFAULT 1,
    CONSTRAINT "PK_notification_settings" PRIMARY KEY (notification_setting_id),
    CONSTRAINT "FK_notification_settings_updated_by" FOREIGN KEY (updated_by) REFERENCES auth.users (user_id),
    CONSTRAINT "FK_notification_settings_user" FOREIGN KEY (user_id) REFERENCES auth.users (user_id)
);

CREATE TABLE notify.notification_templates (
    template_id bigint GENERATED BY DEFAULT AS IDENTITY,
    template_code character varying(100) NOT NULL,
    template_name character varying(255) NOT NULL,
    notification_type character varying(100) NOT NULL,
    title_template character varying(500) NOT NULL,
    body_template text NOT NULL,
    email_subject_template character varying(500),
    email_body_template text,
    default_priority character varying(50) NOT NULL DEFAULT 'medium',
    is_active boolean NOT NULL DEFAULT TRUE,
    created_at timestamp(0) with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    created_by bigint,
    updated_at timestamp(0) with time zone,
    updated_by bigint,
    row_version bigint NOT NULL DEFAULT 1,
    CONSTRAINT "PK_notification_templates" PRIMARY KEY (template_id),
    CONSTRAINT "FK_notification_templates_created_by" FOREIGN KEY (created_by) REFERENCES auth.users (user_id),
    CONSTRAINT "FK_notification_templates_updated_by" FOREIGN KEY (updated_by) REFERENCES auth.users (user_id)
);

CREATE TABLE auth.password_reset_tokens (
    token_id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    token_hash character varying(500) NOT NULL,
    expires_at timestamp(0) with time zone NOT NULL,
    used_at timestamp(0) with time zone,
    created_at timestamp(0) with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    created_by bigint,
    CONSTRAINT "PK_password_reset_tokens" PRIMARY KEY (token_id),
    CONSTRAINT "FK_password_reset_tokens_created_by" FOREIGN KEY (created_by) REFERENCES auth.users (user_id),
    CONSTRAINT "FK_password_reset_tokens_user" FOREIGN KEY (user_id) REFERENCES auth.users (user_id)
);

CREATE TABLE auth.role_permissions (
    role_permission_id bigint GENERATED BY DEFAULT AS IDENTITY,
    role_id bigint NOT NULL,
    permission_id bigint NOT NULL,
    is_allowed boolean NOT NULL DEFAULT TRUE,
    assigned_at timestamp(0) with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    assigned_by bigint,
    CONSTRAINT "PK_role_permissions" PRIMARY KEY (role_permission_id),
    CONSTRAINT "FK_role_permissions_assigned_by" FOREIGN KEY (assigned_by) REFERENCES auth.users (user_id),
    CONSTRAINT "FK_role_permissions_permission" FOREIGN KEY (permission_id) REFERENCES auth.permissions (permission_id),
    CONSTRAINT "FK_role_permissions_role" FOREIGN KEY (role_id) REFERENCES auth.roles (role_id)
);

CREATE TABLE research.sponsors (
    sponsor_id bigint GENERATED BY DEFAULT AS IDENTITY,
    sponsor_code character varying(100) NOT NULL,
    sponsor_name character varying(255) NOT NULL,
    sponsor_type character varying(100),
    contact_person character varying(255),
    contact_email character varying(255),
    contact_phone character varying(50),
    address character varying(1000),
    is_active boolean NOT NULL DEFAULT TRUE,
    created_at timestamp(0) with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    created_by bigint,
    updated_at timestamp(0) with time zone,
    updated_by bigint,
    deleted_at timestamp(0) with time zone,
    deleted_by bigint,
    row_version bigint NOT NULL DEFAULT 1,
    CONSTRAINT "PK_sponsors" PRIMARY KEY (sponsor_id),
    CONSTRAINT "FK_sponsors_created_by" FOREIGN KEY (created_by) REFERENCES auth.users (user_id),
    CONSTRAINT "FK_sponsors_updated_by" FOREIGN KEY (updated_by) REFERENCES auth.users (user_id)
);

CREATE TABLE training.training_events (
    event_id bigint GENERATED BY DEFAULT AS IDENTITY,
    event_code character varying(100) NOT NULL,
    event_title character varying(500) NOT NULL,
    event_description text,
    event_year integer NOT NULL,
    event_month integer NOT NULL,
    planned_date date,
    start_time time(0) without time zone,
    end_time time(0) without time zone,
    actual_date date,
    category_id bigint,
    event_type character varying(100) NOT NULL,
    plan_type character varying(100) NOT NULL,
    department_id bigint,
    responsible_user_id bigint,
    location character varying(500),
    delivery_mode character varying(100) NOT NULL DEFAULT 'offline',
    planned_attendees integer,
    actual_attendees integer,
    event_status character varying(100) NOT NULL DEFAULT 'planned',
    cancellation_reason text,
    notes text,
    is_active boolean NOT NULL DEFAULT TRUE,
    created_at timestamp(0) with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    created_by bigint,
    updated_at timestamp(0) with time zone,
    updated_by bigint,
    deleted_at timestamp(0) with time zone,
    deleted_by bigint,
    row_version bigint NOT NULL DEFAULT 1,
    CONSTRAINT "PK_training_events" PRIMARY KEY (event_id),
    CONSTRAINT "FK_training_events_category" FOREIGN KEY (category_id) REFERENCES training.event_categories (category_id),
    CONSTRAINT "FK_training_events_created_by" FOREIGN KEY (created_by) REFERENCES auth.users (user_id),
    CONSTRAINT "FK_training_events_department" FOREIGN KEY (department_id) REFERENCES ref.departments (department_id),
    CONSTRAINT "FK_training_events_responsible" FOREIGN KEY (responsible_user_id) REFERENCES auth.users (user_id),
    CONSTRAINT "FK_training_events_updated_by" FOREIGN KEY (updated_by) REFERENCES auth.users (user_id)
);

CREATE TABLE auth.user_preferences (
    preference_id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    appearance_mode character varying(50) NOT NULL DEFAULT 'system',
    language_code character varying(20) NOT NULL DEFAULT 'vi-VN',
    enable_in_app_notification boolean NOT NULL DEFAULT TRUE,
    enable_email_notification boolean NOT NULL,
    receive_deadline_notification boolean NOT NULL DEFAULT TRUE,
    receive_training_notification boolean NOT NULL DEFAULT TRUE,
    receive_ethics_notification boolean NOT NULL DEFAULT TRUE,
    auto_mark_read_on_open boolean NOT NULL,
    created_at timestamp(0) with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    updated_at timestamp(0) with time zone,
    CONSTRAINT "PK_user_preferences" PRIMARY KEY (preference_id),
    CONSTRAINT "FK_user_preferences_user" FOREIGN KEY (user_id) REFERENCES auth.users (user_id)
);

CREATE TABLE auth.user_roles (
    user_role_id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    role_id bigint NOT NULL,
    assigned_at timestamp(0) with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    assigned_by bigint,
    is_active boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT "PK_user_roles" PRIMARY KEY (user_role_id),
    CONSTRAINT "FK_user_roles_assigned_by" FOREIGN KEY (assigned_by) REFERENCES auth.users (user_id),
    CONSTRAINT "FK_user_roles_role" FOREIGN KEY (role_id) REFERENCES auth.roles (role_id),
    CONSTRAINT "FK_user_roles_user" FOREIGN KEY (user_id) REFERENCES auth.users (user_id)
);

CREATE TABLE notify.notification_rules (
    rule_id bigint GENERATED BY DEFAULT AS IDENTITY,
    rule_code character varying(100) NOT NULL,
    rule_name character varying(255) NOT NULL,
    object_type character varying(100) NOT NULL,
    condition_type character varying(100) NOT NULL,
    reminder_days integer NOT NULL DEFAULT 1,
    channel_in_app boolean NOT NULL DEFAULT TRUE,
    channel_email boolean NOT NULL,
    priority_level character varying(50) NOT NULL DEFAULT 'medium',
    template_id bigint,
    repeat_if_overdue boolean NOT NULL,
    repeat_interval_days integer,
    is_active boolean NOT NULL DEFAULT TRUE,
    description character varying(1000),
    created_at timestamp(0) with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    created_by bigint,
    updated_at timestamp(0) with time zone,
    updated_by bigint,
    deleted_at timestamp(0) with time zone,
    deleted_by bigint,
    row_version bigint NOT NULL DEFAULT 1,
    CONSTRAINT "PK_notification_rules" PRIMARY KEY (rule_id),
    CONSTRAINT "FK_notification_rules_created_by" FOREIGN KEY (created_by) REFERENCES auth.users (user_id),
    CONSTRAINT "FK_notification_rules_template" FOREIGN KEY (template_id) REFERENCES notify.notification_templates (template_id),
    CONSTRAINT "FK_notification_rules_updated_by" FOREIGN KEY (updated_by) REFERENCES auth.users (user_id)
);

CREATE TABLE research.research_projects (
    project_id bigint GENERATED BY DEFAULT AS IDENTITY,
    project_code character varying(100) NOT NULL,
    project_title character varying(500) NOT NULL,
    project_description text,
    lead_department_id bigint,
    principal_investigator_id bigint,
    sponsor_id bigint,
    sponsor_name_text character varying(255),
    research_type character varying(100),
    protocol_number character varying(100),
    protocol_version character varying(50),
    ethics_status character varying(100) NOT NULL DEFAULT 'not_required',
    ethics_approval_number character varying(100),
    ethics_approval_date date,
    ethics_expiry_date date,
    planned_start_date date,
    planned_end_date date,
    actual_start_date date,
    actual_end_date date,
    current_phase_name character varying(255),
    progress_percent numeric(5,2) NOT NULL,
    project_status character varying(100) NOT NULL DEFAULT 'not_started',
    health_status character varying(100) NOT NULL DEFAULT 'on_track',
    risk_level character varying(50) NOT NULL DEFAULT 'low',
    priority_level character varying(50) NOT NULL DEFAULT 'normal',
    notes text,
    is_active boolean NOT NULL DEFAULT TRUE,
    created_at timestamp(0) with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    created_by bigint,
    updated_at timestamp(0) with time zone,
    updated_by bigint,
    deleted_at timestamp(0) with time zone,
    deleted_by bigint,
    row_version bigint NOT NULL DEFAULT 1,
    CONSTRAINT "PK_research_projects" PRIMARY KEY (project_id),
    CONSTRAINT "FK_research_projects_created_by" FOREIGN KEY (created_by) REFERENCES auth.users (user_id),
    CONSTRAINT "FK_research_projects_department" FOREIGN KEY (lead_department_id) REFERENCES ref.departments (department_id),
    CONSTRAINT "FK_research_projects_pi" FOREIGN KEY (principal_investigator_id) REFERENCES auth.users (user_id),
    CONSTRAINT "FK_research_projects_sponsor" FOREIGN KEY (sponsor_id) REFERENCES research.sponsors (sponsor_id),
    CONSTRAINT "FK_research_projects_updated_by" FOREIGN KEY (updated_by) REFERENCES auth.users (user_id)
);

CREATE TABLE training.training_event_logs (
    event_log_id bigint GENERATED BY DEFAULT AS IDENTITY,
    event_id bigint NOT NULL,
    action_type character varying(100) NOT NULL,
    old_value_json jsonb,
    new_value_json jsonb,
    note text,
    created_at timestamp(0) with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    created_by bigint,
    CONSTRAINT "PK_training_event_logs" PRIMARY KEY (event_log_id),
    CONSTRAINT "FK_training_event_logs_created_by" FOREIGN KEY (created_by) REFERENCES auth.users (user_id),
    CONSTRAINT "FK_training_event_logs_event" FOREIGN KEY (event_id) REFERENCES training.training_events (event_id)
);

CREATE TABLE training.training_event_participants (
    participant_id bigint GENERATED BY DEFAULT AS IDENTITY,
    event_id bigint NOT NULL,
    user_id bigint,
    participant_name character varying(255) NOT NULL,
    participant_email character varying(255),
    department_id bigint,
    attendance_status character varying(50) NOT NULL DEFAULT 'registered',
    checked_in_at timestamp(0) with time zone,
    notes character varying(1000),
    created_at timestamp(0) with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    created_by bigint,
    CONSTRAINT "PK_training_event_participants" PRIMARY KEY (participant_id),
    CONSTRAINT "FK_training_event_participants_created_by" FOREIGN KEY (created_by) REFERENCES auth.users (user_id),
    CONSTRAINT "FK_training_event_participants_department" FOREIGN KEY (department_id) REFERENCES ref.departments (department_id),
    CONSTRAINT "FK_training_event_participants_event" FOREIGN KEY (event_id) REFERENCES training.training_events (event_id),
    CONSTRAINT "FK_training_event_participants_user" FOREIGN KEY (user_id) REFERENCES auth.users (user_id)
);

CREATE TABLE notify.notifications (
    notification_id bigint GENERATED BY DEFAULT AS IDENTITY,
    notification_type character varying(100) NOT NULL,
    category character varying(100) NOT NULL,
    title character varying(500) NOT NULL,
    message text NOT NULL,
    priority_level character varying(50) NOT NULL DEFAULT 'medium',
    related_entity_type character varying(100),
    related_entity_id bigint,
    related_entity_code character varying(100),
    action_url character varying(1000),
    suggested_action character varying(255),
    generated_by_rule_id bigint,
    created_at timestamp(0) with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    expires_at timestamp(0) with time zone,
    is_deleted boolean NOT NULL,
    deleted_at timestamp(0) with time zone,
    CONSTRAINT "PK_notifications" PRIMARY KEY (notification_id),
    CONSTRAINT "FK_notifications_rule" FOREIGN KEY (generated_by_rule_id) REFERENCES notify.notification_rules (rule_id)
);

CREATE TABLE research.project_members (
    project_member_id bigint GENERATED BY DEFAULT AS IDENTITY,
    project_id bigint NOT NULL,
    user_id bigint NOT NULL,
    member_role character varying(100) NOT NULL,
    responsibility character varying(1000),
    joined_at date NOT NULL DEFAULT (CURRENT_DATE),
    left_at date,
    is_active boolean NOT NULL DEFAULT TRUE,
    created_at timestamp(0) with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    created_by bigint,
    CONSTRAINT "PK_project_members" PRIMARY KEY (project_member_id),
    CONSTRAINT "FK_project_members_created_by" FOREIGN KEY (created_by) REFERENCES auth.users (user_id),
    CONSTRAINT "FK_project_members_project" FOREIGN KEY (project_id) REFERENCES research.research_projects (project_id),
    CONSTRAINT "FK_project_members_user" FOREIGN KEY (user_id) REFERENCES auth.users (user_id)
);

CREATE TABLE research.project_phases (
    phase_id bigint GENERATED BY DEFAULT AS IDENTITY,
    project_id bigint NOT NULL,
    phase_code character varying(100),
    phase_name character varying(255) NOT NULL,
    phase_description text,
    owner_user_id bigint,
    planned_start_date date,
    planned_end_date date,
    deadline_date date,
    actual_start_date date,
    actual_end_date date,
    progress_percent numeric(5,2) NOT NULL,
    phase_status character varying(100) NOT NULL DEFAULT 'not_started',
    sort_order integer NOT NULL,
    notes text,
    is_active boolean NOT NULL DEFAULT TRUE,
    created_at timestamp(0) with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    created_by bigint,
    updated_at timestamp(0) with time zone,
    updated_by bigint,
    deleted_at timestamp(0) with time zone,
    deleted_by bigint,
    row_version bigint NOT NULL DEFAULT 1,
    CONSTRAINT "PK_project_phases" PRIMARY KEY (phase_id),
    CONSTRAINT "FK_project_phases_created_by" FOREIGN KEY (created_by) REFERENCES auth.users (user_id),
    CONSTRAINT "FK_project_phases_owner" FOREIGN KEY (owner_user_id) REFERENCES auth.users (user_id),
    CONSTRAINT "FK_project_phases_project" FOREIGN KEY (project_id) REFERENCES research.research_projects (project_id),
    CONSTRAINT "FK_project_phases_updated_by" FOREIGN KEY (updated_by) REFERENCES auth.users (user_id)
);

CREATE TABLE notify.notification_recipients (
    notification_recipient_id bigint GENERATED BY DEFAULT AS IDENTITY,
    notification_id bigint NOT NULL,
    user_id bigint NOT NULL,
    is_read boolean NOT NULL,
    read_at timestamp(0) with time zone,
    is_dismissed boolean NOT NULL,
    dismissed_at timestamp(0) with time zone,
    delivered_in_app_at timestamp(0) with time zone,
    delivered_email_at timestamp(0) with time zone,
    email_send_status character varying(50),
    email_failure_reason character varying(1000),
    created_at timestamp(0) with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_notification_recipients" PRIMARY KEY (notification_recipient_id),
    CONSTRAINT "FK_notification_recipients_notification" FOREIGN KEY (notification_id) REFERENCES notify.notifications (notification_id),
    CONSTRAINT "FK_notification_recipients_user" FOREIGN KEY (user_id) REFERENCES auth.users (user_id)
);

CREATE TABLE research.project_milestones (
    milestone_id bigint GENERATED BY DEFAULT AS IDENTITY,
    project_id bigint NOT NULL,
    phase_id bigint,
    milestone_code character varying(100),
    milestone_name character varying(255) NOT NULL,
    milestone_description text,
    due_date date NOT NULL,
    completed_date date,
    owner_user_id bigint,
    milestone_status character varying(100) NOT NULL DEFAULT 'not_started',
    priority_level character varying(50) NOT NULL DEFAULT 'normal',
    notes text,
    is_active boolean NOT NULL DEFAULT TRUE,
    created_at timestamp(0) with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    created_by bigint,
    updated_at timestamp(0) with time zone,
    updated_by bigint,
    deleted_at timestamp(0) with time zone,
    deleted_by bigint,
    row_version bigint NOT NULL DEFAULT 1,
    CONSTRAINT "PK_project_milestones" PRIMARY KEY (milestone_id),
    CONSTRAINT "FK_project_milestones_created_by" FOREIGN KEY (created_by) REFERENCES auth.users (user_id),
    CONSTRAINT "FK_project_milestones_owner" FOREIGN KEY (owner_user_id) REFERENCES auth.users (user_id),
    CONSTRAINT "FK_project_milestones_phase" FOREIGN KEY (phase_id) REFERENCES research.project_phases (phase_id),
    CONSTRAINT "FK_project_milestones_project" FOREIGN KEY (project_id) REFERENCES research.research_projects (project_id),
    CONSTRAINT "FK_project_milestones_updated_by" FOREIGN KEY (updated_by) REFERENCES auth.users (user_id)
);

CREATE TABLE research.project_deadlines (
    deadline_id bigint GENERATED BY DEFAULT AS IDENTITY,
    project_id bigint,
    phase_id bigint,
    milestone_id bigint,
    deadline_type character varying(100) NOT NULL,
    deadline_title character varying(255) NOT NULL,
    deadline_description text,
    due_date date NOT NULL,
    completed_at timestamp(0) with time zone,
    responsible_user_id bigint,
    priority_level character varying(50) NOT NULL DEFAULT 'normal',
    deadline_status character varying(100) NOT NULL DEFAULT 'open',
    created_at timestamp(0) with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    created_by bigint,
    updated_at timestamp(0) with time zone,
    updated_by bigint,
    deleted_at timestamp(0) with time zone,
    deleted_by bigint,
    row_version bigint NOT NULL DEFAULT 1,
    CONSTRAINT "PK_project_deadlines" PRIMARY KEY (deadline_id),
    CONSTRAINT "FK_project_deadlines_created_by" FOREIGN KEY (created_by) REFERENCES auth.users (user_id),
    CONSTRAINT "FK_project_deadlines_milestone" FOREIGN KEY (milestone_id) REFERENCES research.project_milestones (milestone_id),
    CONSTRAINT "FK_project_deadlines_phase" FOREIGN KEY (phase_id) REFERENCES research.project_phases (phase_id),
    CONSTRAINT "FK_project_deadlines_project" FOREIGN KEY (project_id) REFERENCES research.research_projects (project_id),
    CONSTRAINT "FK_project_deadlines_responsible" FOREIGN KEY (responsible_user_id) REFERENCES auth.users (user_id),
    CONSTRAINT "FK_project_deadlines_updated_by" FOREIGN KEY (updated_by) REFERENCES auth.users (user_id)
);

CREATE TABLE research.project_documents (
    document_id bigint GENERATED BY DEFAULT AS IDENTITY,
    project_id bigint NOT NULL,
    phase_id bigint,
    milestone_id bigint,
    document_type character varying(100) NOT NULL,
    document_title character varying(255) NOT NULL,
    file_name character varying(255),
    file_url character varying(1000),
    file_size_bytes bigint,
    mime_type character varying(255),
    version_label character varying(50),
    uploaded_at timestamp(0) with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    uploaded_by bigint,
    is_active boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT "PK_project_documents" PRIMARY KEY (document_id),
    CONSTRAINT "FK_project_documents_milestone" FOREIGN KEY (milestone_id) REFERENCES research.project_milestones (milestone_id),
    CONSTRAINT "FK_project_documents_phase" FOREIGN KEY (phase_id) REFERENCES research.project_phases (phase_id),
    CONSTRAINT "FK_project_documents_project" FOREIGN KEY (project_id) REFERENCES research.research_projects (project_id),
    CONSTRAINT "FK_project_documents_uploaded_by" FOREIGN KEY (uploaded_by) REFERENCES auth.users (user_id)
);

CREATE INDEX "IX_activity_logs_module" ON audit.activity_logs (module_code, action_type, occurred_at DESC);

CREATE INDEX "IX_activity_logs_occurred" ON audit.activity_logs (occurred_at DESC);

CREATE INDEX "IX_activity_logs_user" ON audit.activity_logs (user_id, occurred_at DESC);

CREATE INDEX "IX_data_change_logs_user_id" ON audit.data_change_logs (user_id);

CREATE INDEX "IX_departments_parent_department_id" ON ref.departments (parent_department_id);

CREATE UNIQUE INDEX "UQ_departments_code" ON ref.departments (department_code);

CREATE UNIQUE INDEX "UQ_event_categories_code" ON training.event_categories (category_code);

CREATE INDEX "IX_login_events_time" ON audit.login_events (occurred_at DESC, success);

CREATE INDEX "IX_login_events_user_time" ON audit.login_events (user_id, occurred_at DESC);

CREATE INDEX "IX_login_sessions_user_id" ON auth.login_sessions (user_id);

CREATE INDEX "IX_notification_recipients_user_read" ON notify.notification_recipients (user_id, is_read, created_at DESC);

CREATE UNIQUE INDEX "UQ_notification_recipients" ON notify.notification_recipients (notification_id, user_id);

CREATE INDEX "IX_notification_rules_active" ON notify.notification_rules (is_active, object_type, condition_type, reminder_days);

CREATE INDEX "IX_notification_rules_created_by" ON notify.notification_rules (created_by);

CREATE INDEX "IX_notification_rules_template_id" ON notify.notification_rules (template_id);

CREATE INDEX "IX_notification_rules_updated_by" ON notify.notification_rules (updated_by);

CREATE UNIQUE INDEX "UQ_notification_rules_code" ON notify.notification_rules (rule_code);

CREATE INDEX "IX_notification_settings_updated_by" ON notify.notification_settings (updated_by);

CREATE INDEX "IX_notification_settings_user_id" ON notify.notification_settings (user_id);

CREATE INDEX "IX_notification_templates_created_by" ON notify.notification_templates (created_by);

CREATE INDEX "IX_notification_templates_updated_by" ON notify.notification_templates (updated_by);

CREATE UNIQUE INDEX "UQ_notification_templates_code" ON notify.notification_templates (template_code);

CREATE INDEX "IX_notifications_created" ON notify.notifications (created_at DESC, category, priority_level);

CREATE INDEX "IX_notifications_generated_by_rule_id" ON notify.notifications (generated_by_rule_id);

CREATE INDEX "IX_password_reset_tokens_created_by" ON auth.password_reset_tokens (created_by);

CREATE INDEX "IX_password_reset_tokens_user_id" ON auth.password_reset_tokens (user_id);

CREATE UNIQUE INDEX "UQ_permissions_code" ON auth.permissions (permission_code);

CREATE UNIQUE INDEX "UQ_permissions_module_action" ON auth.permissions (module_code, action_code);

CREATE INDEX "IX_project_deadlines_created_by" ON research.project_deadlines (created_by);

CREATE INDEX "IX_project_deadlines_due" ON research.project_deadlines (due_date, deadline_status, priority_level);

CREATE INDEX "IX_project_deadlines_milestone_id" ON research.project_deadlines (milestone_id);

CREATE INDEX "IX_project_deadlines_phase_id" ON research.project_deadlines (phase_id);

CREATE INDEX "IX_project_deadlines_project" ON research.project_deadlines (project_id, deadline_status);

CREATE INDEX "IX_project_deadlines_responsible_user_id" ON research.project_deadlines (responsible_user_id);

CREATE INDEX "IX_project_deadlines_updated_by" ON research.project_deadlines (updated_by);

CREATE INDEX "IX_project_documents_milestone_id" ON research.project_documents (milestone_id);

CREATE INDEX "IX_project_documents_phase_id" ON research.project_documents (phase_id);

CREATE INDEX "IX_project_documents_project_id" ON research.project_documents (project_id);

CREATE INDEX "IX_project_documents_uploaded_by" ON research.project_documents (uploaded_by);

CREATE INDEX "IX_project_members_created_by" ON research.project_members (created_by);

CREATE INDEX "IX_project_members_user_id" ON research.project_members (user_id);

CREATE UNIQUE INDEX "UQ_project_members_project_user_role" ON research.project_members (project_id, user_id, member_role);

CREATE INDEX "IX_project_milestones_created_by" ON research.project_milestones (created_by);

CREATE INDEX "IX_project_milestones_due" ON research.project_milestones (due_date, milestone_status, priority_level);

CREATE INDEX "IX_project_milestones_owner_user_id" ON research.project_milestones (owner_user_id);

CREATE INDEX "IX_project_milestones_phase_id" ON research.project_milestones (phase_id);

CREATE INDEX "IX_project_milestones_project_id" ON research.project_milestones (project_id);

CREATE INDEX "IX_project_milestones_updated_by" ON research.project_milestones (updated_by);

CREATE INDEX "IX_project_phases_created_by" ON research.project_phases (created_by);

CREATE INDEX "IX_project_phases_deadline" ON research.project_phases (deadline_date, phase_status);

CREATE INDEX "IX_project_phases_owner_user_id" ON research.project_phases (owner_user_id);

CREATE INDEX "IX_project_phases_project_sort" ON research.project_phases (project_id, sort_order, planned_start_date);

CREATE INDEX "IX_project_phases_updated_by" ON research.project_phases (updated_by);

CREATE INDEX "IX_research_projects_created_by" ON research.research_projects (created_by);

CREATE INDEX "IX_research_projects_department" ON research.research_projects (lead_department_id, project_status);

CREATE INDEX "IX_research_projects_ethics" ON research.research_projects (ethics_status, ethics_expiry_date);

CREATE INDEX "IX_research_projects_principal_investigator_id" ON research.research_projects (principal_investigator_id);

CREATE INDEX "IX_research_projects_sponsor_id" ON research.research_projects (sponsor_id);

CREATE INDEX "IX_research_projects_status_year" ON research.research_projects (project_status, planned_start_date, planned_end_date);

CREATE INDEX "IX_research_projects_updated_by" ON research.research_projects (updated_by);

CREATE UNIQUE INDEX "UQ_research_projects_code" ON research.research_projects (project_code);

CREATE INDEX "IX_role_permissions_assigned_by" ON auth.role_permissions (assigned_by);

CREATE INDEX "IX_role_permissions_permission_id" ON auth.role_permissions (permission_id);

CREATE INDEX "IX_role_permissions_role" ON auth.role_permissions (role_id, permission_id);

CREATE UNIQUE INDEX "UQ_role_permissions_role_permission" ON auth.role_permissions (role_id, permission_id);

CREATE UNIQUE INDEX "UQ_roles_code" ON auth.roles (role_code);

CREATE INDEX "IX_sponsors_created_by" ON research.sponsors (created_by);

CREATE INDEX "IX_sponsors_updated_by" ON research.sponsors (updated_by);

CREATE UNIQUE INDEX "UQ_sponsors_code" ON research.sponsors (sponsor_code);

CREATE UNIQUE INDEX "UQ_system_settings_key" ON ref.system_settings (setting_key);

CREATE INDEX "IX_training_event_logs_created_by" ON training.training_event_logs (created_by);

CREATE INDEX "IX_training_event_logs_event_id" ON training.training_event_logs (event_id);

CREATE INDEX "IX_training_event_participants_created_by" ON training.training_event_participants (created_by);

CREATE INDEX "IX_training_event_participants_department_id" ON training.training_event_participants (department_id);

CREATE INDEX "IX_training_event_participants_event_id" ON training.training_event_participants (event_id);

CREATE INDEX "IX_training_event_participants_user_id" ON training.training_event_participants (user_id);

CREATE INDEX "IX_training_events_category_id" ON training.training_events (category_id);

CREATE INDEX "IX_training_events_created_by" ON training.training_events (created_by);

CREATE INDEX "IX_training_events_date_status" ON training.training_events (planned_date, event_status, plan_type);

CREATE INDEX "IX_training_events_department" ON training.training_events (department_id, event_year, event_month);

CREATE INDEX "IX_training_events_responsible_user_id" ON training.training_events (responsible_user_id);

CREATE INDEX "IX_training_events_updated_by" ON training.training_events (updated_by);

CREATE INDEX "IX_training_events_year_month" ON training.training_events (event_year, event_month);

CREATE UNIQUE INDEX "UQ_training_events_code" ON training.training_events (event_code);

CREATE UNIQUE INDEX "UQ_user_preferences_user" ON auth.user_preferences (user_id);

CREATE INDEX "IX_user_roles_assigned_by" ON auth.user_roles (assigned_by);

CREATE INDEX "IX_user_roles_role_id" ON auth.user_roles (role_id);

CREATE INDEX "IX_user_roles_user_active" ON auth.user_roles (user_id, is_active);

CREATE UNIQUE INDEX "UQ_user_roles_user_role" ON auth.user_roles (user_id, role_id);

CREATE INDEX "IX_users_department_status" ON auth.users (department_id, account_status);

CREATE UNIQUE INDEX "UQ_users_email" ON auth.users (email);

CREATE UNIQUE INDEX "UQ_users_username" ON auth.users (username);

CREATE OR REPLACE VIEW research.v_research_project_overview AS
SELECT
    p.project_id,
    p.project_code,
    p.project_title,
    d.department_name AS lead_department_name,
    u.full_name AS principal_investigator_name,
    COALESCE(s.sponsor_name, p.sponsor_name_text) AS sponsor_name,
    p.protocol_number,
    p.protocol_version,
    p.ethics_status,
    p.ethics_expiry_date,
    p.planned_start_date,
    p.planned_end_date,
    p.progress_percent,
    p.current_phase_name,
    p.project_status,
    p.health_status,
    p.risk_level,
    nd.due_date AS next_due_date,
    nd.deadline_title AS next_due_title,
    CASE
        WHEN p.ethics_expiry_date IS NOT NULL AND p.ethics_expiry_date < CURRENT_DATE THEN 1
        ELSE 0
    END AS is_ethics_expired,
    CASE
        WHEN p.ethics_expiry_date IS NOT NULL
            AND p.ethics_expiry_date BETWEEN CURRENT_DATE AND (CURRENT_DATE + INTERVAL '30 days')::date THEN 1
        ELSE 0
    END AS is_ethics_expiring_soon
FROM research.research_projects p
LEFT JOIN ref.departments d ON d.department_id = p.lead_department_id
LEFT JOIN auth.users u ON u.user_id = p.principal_investigator_id
LEFT JOIN research.sponsors s ON s.sponsor_id = p.sponsor_id
LEFT JOIN LATERAL (
    SELECT deadline_title, due_date
    FROM research.project_deadlines dl
    WHERE dl.project_id = p.project_id
        AND dl.deleted_at IS NULL
        AND dl.deadline_status <> 'completed'
    ORDER BY dl.due_date
    LIMIT 1
) nd ON true
WHERE p.deleted_at IS NULL;

CREATE OR REPLACE VIEW training.v_training_monthly_summary AS
SELECT
    event_year,
    event_month,
    COUNT(*) FILTER (WHERE plan_type = 'planned')::int AS planned_count,
    COUNT(*) FILTER (WHERE plan_type = 'additional')::int AS additional_count,
    COUNT(*) FILTER (WHERE event_status = 'completed')::int AS actual_count,
    COUNT(*)::int AS total_plan_count,
    COUNT(*) FILTER (WHERE event_status <> 'completed')::int AS not_completed_count,
    CASE
        WHEN COUNT(*) = 0 THEN 0::numeric(5,2)
        ELSE ROUND((COUNT(*) FILTER (WHERE event_status = 'completed')::numeric / COUNT(*)::numeric) * 100, 2)::numeric(5,2)
    END AS completion_rate
FROM training.training_events
WHERE deleted_at IS NULL AND is_active = true
GROUP BY event_year, event_month;

CREATE OR REPLACE VIEW notify.v_user_notification_inbox AS
SELECT
    nr.notification_recipient_id,
    n.notification_id,
    nr.user_id,
    n.notification_type,
    n.category,
    n.title,
    n.message,
    n.priority_level,
    n.related_entity_type,
    n.related_entity_id,
    n.related_entity_code,
    n.action_url,
    n.suggested_action,
    n.created_at,
    nr.is_read,
    nr.read_at,
    nr.is_dismissed,
    nr.dismissed_at
FROM notify.notification_recipients nr
JOIN notify.notifications n ON n.notification_id = nr.notification_id
WHERE n.is_deleted = false;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260714013637_InitialPostgreSql', '8.0.11');

COMMIT;

