export const DEPARTMENTS = [
  "Tất cả",
  "QLCL",
  "KHTH",
  "Điều dưỡng",
  "ĐT&NCKH",
  "Xét nghiệm",
  "Chẩn đoán hình ảnh",
  "Dược",
  "Kiểm soát nhiễm khuẩn",
  "Dinh dưỡng",
  "Hồi sức cấp cứu",
  "Khoa khám bệnh",
  "Vật lý trị liệu",
  "Thần kinh đột quỵ",
  "Thần kinh đột quỵ 2",
  "Nội tổng hợp",
  "Nội tổng hợp 2",
  "Ngoại tổng hợp",
  "PTGMHS - ICU",
  "PTGMHS - DSA",
  "PTGMHS - PM",
];
